// auth
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_INITIATED = "LOGIN_INITIATED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
export const LOGOUT_INITIATED = "LOGOUT_INITIATED";
export const SIGNUP_INITIATED = "SIGNUP_INITIATED";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

//notes
export const CREATE_NOTES_INITIATED = "CREATE_NOTES_INITIATED";
export const CREATE_NOTES_FAILED = "CREATE_NOTES_FAILED"
export const CREATE_NOTES_SUCCESS = "CREATE_NOTES_SUCCESS";
export const GET_NOTES_INITIATED = "GET_NOTES_INITIATED";
export const GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS";
export const GET_NOTES_FAILED = "GET_NOTES_FAILED";

//feed
export const GET_TRACKS_INITIATED = "GET_TRACKS_INITIATED";
export const GET_TRACKS_SUCCESS = "GET_TRACKS_SUCCESS";
export const GET_TRACKS_FAILED = "GET_TRACKS_FAILED";